[2025-10-13 07:48:04] NOTICE: Route not found {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 08:05:44] NOTICE: Route not found {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 08:17:51] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(107): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:17:52] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(107): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:32:55] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:32:55] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:32:57] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:33:37] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:33:38] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:33:38] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:33:45] ERROR: Template 'Main\index\index.phtml' not found at: C:\xampp\htdocs\new\app\views\Main\index\index.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(41): Core\\Mvc\\View->findTemplate('Main\\\\index\\\\inde...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/index/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/index/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:36:50] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:36:51] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:15] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:16] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:16] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:17] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:17] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:19] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:20] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:21] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:37:36] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:38:22] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:38:23] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:38:23] ERROR: Template 'layout\.phtml' not found at: C:\xampp\htdocs\new\app\views\layout\.phtml {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":82,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(46): Core\\Mvc\\View->findTemplate('layout\\\\.phtml')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#3 [internal function]: Main\\Controller\\Hello->indexAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-13 08:38:52] ERROR: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 08:38:53] ERROR: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 08:38:53] ERROR: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 09:27:16] ERROR: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 09:36:41] WARNING: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 09:36:42] WARNING: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 09:36:42] WARNING: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 09:37:36] WARNING: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 09:37:37] WARNING: Method or helper 'messages' not found in View. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php","line":161,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\layout\\default.phtml(72): Core\\Mvc\\View->__call('messages', Array)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(47): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\Hello.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#7 [internal function]: Main\\Controller\\Hello->indexAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(118): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 09:38:01] WARNING: Route not found {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 09:38:03] WARNING: Route not found {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 09:38:05] WARNING: Route not found {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 09:38:06] WARNING: Route not found {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 09:38:08] WARNING: Route not found {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 09:38:08] WARNING: Route not found {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 09:38:14] WARNING: Route not found {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php","line":86,"trace":"#0 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#1 {main}"}
[2025-10-13 11:18:13] ERROR: Service 'dispatcher' not found or cannot be resolved. {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(72): Core\\Di\\Container->get('dispatcher')\n#1 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#2 {main}"}
[2025-10-13 12:49:10] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":5,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 5)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(5): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 12:49:11] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":5,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 5)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(5): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 12:49:25] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of this year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":5,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 5)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(5): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 12:49:26] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of this year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":5,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 5)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(5): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 12:52:51] ERROR: Call to a member function format() on bool {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":7,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include()\n#1 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#6 [internal function]: Main\\Controller\\HelloController->indexAction()\n#7 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#9 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#10 {main}"}
[2025-10-13 12:52:51] ERROR: Call to a member function format() on bool {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":7,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include()\n#1 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#6 [internal function]: Main\\Controller\\HelloController->indexAction()\n#7 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#9 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#10 {main}"}
[2025-10-13 13:02:49] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of this year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:02:50] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of this year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:02:51] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of this year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:01] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month current year) at position 12 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month cur...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:02] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month current year) at position 12 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month cur...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:02] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month current year) at position 12 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month cur...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:17] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:18] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:23] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month year) at position 12 (y): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month yea...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:31] ERROR: DateTimeImmutable::modify(): Failed to parse time string (januar month year) at position 0 (j): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('januar month ye...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:32] ERROR: DateTimeImmutable::modify(): Failed to parse time string (januar month year) at position 0 (j): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('januar month ye...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:37] ERROR: DateTimeImmutable::modify(): Failed to parse time string (januar this year) at position 0 (j): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('januar this yea...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:03:38] ERROR: DateTimeImmutable::modify(): Failed to parse time string (januar this year) at position 0 (j): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('januar this yea...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:04:08] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first day current year) at position 10 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first day curre...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:04:09] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first day current year) at position 10 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first day curre...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:04:16] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first day of year) at position 13 (y): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first day of ye...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:04:16] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first day of year) at position 13 (y): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first day of ye...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:16] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:17] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:17] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:17] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:18] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:24] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month of current year) at position 12 (o): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month of ...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:48] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month current year) at position 12 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month cur...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:48] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month current year) at position 12 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month cur...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 13:05:48] ERROR: DateTimeImmutable::modify(): Failed to parse time string (first month current year) at position 12 (c): The timezone could not be found in the database {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml","line":6,"trace":"#0 [internal function]: {closure}(2, 'DateTimeImmutab...', 'C:\\\\xampp\\\\htdocs...', 6)\n#1 C:\\xampp\\htdocs\\new\\app\\views\\main\\hello\\index.phtml(6): DateTimeImmutable->modify('first month cur...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#3 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('Main/hello/inde...', Array)\n#7 C:\\xampp\\htdocs\\new\\app\\Main\\Controller\\HelloController.php(23): Core\\Mvc\\Controller->render('Main/hello/inde...', Array)\n#8 [internal function]: Main\\Controller\\HelloController->indexAction()\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#10 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#11 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#12 {main}"}
[2025-10-13 14:23:47] ERROR: str_starts_with(): Argument #1 ($haystack) must be of type string, Core\Http\Request given {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php","line":33,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(33): str_starts_with(Object(Core\\Http\\Request), '/')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(19): Core\\UI\\Layout->isActive('/')\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Provider\\ViewServiceProvider.php(42): Core\\UI\\Layout->addNav('Dashboard', 'calendar3', '/')\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Events\\Manager.php(57): Main\\Provider\\ViewServiceProvider->Main\\Provider\\{closure}(Object(Core\\Events\\Event))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\AbstractModule.php(69): Core\\Events\\Manager->trigger(Object(Core\\Events\\Event), Object(Main\\Module))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(51): Core\\Mvc\\AbstractModule->initialize('Main', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#7 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#8 {main}"}
[2025-10-13 14:23:48] ERROR: str_starts_with(): Argument #1 ($haystack) must be of type string, Core\Http\Request given {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php","line":33,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(33): str_starts_with(Object(Core\\Http\\Request), '/')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(19): Core\\UI\\Layout->isActive('/')\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Provider\\ViewServiceProvider.php(42): Core\\UI\\Layout->addNav('Dashboard', 'calendar3', '/')\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Events\\Manager.php(57): Main\\Provider\\ViewServiceProvider->Main\\Provider\\{closure}(Object(Core\\Events\\Event))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\AbstractModule.php(69): Core\\Events\\Manager->trigger(Object(Core\\Events\\Event), Object(Main\\Module))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(51): Core\\Mvc\\AbstractModule->initialize('Main', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#7 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#8 {main}"}
[2025-10-13 14:23:48] ERROR: str_starts_with(): Argument #1 ($haystack) must be of type string, Core\Http\Request given {"request_uri":"/","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php","line":33,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(33): str_starts_with(Object(Core\\Http\\Request), '/')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(19): Core\\UI\\Layout->isActive('/')\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Provider\\ViewServiceProvider.php(42): Core\\UI\\Layout->addNav('Dashboard', 'calendar3', '/')\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Events\\Manager.php(57): Main\\Provider\\ViewServiceProvider->Main\\Provider\\{closure}(Object(Core\\Events\\Event))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\AbstractModule.php(69): Core\\Events\\Manager->trigger(Object(Core\\Events\\Event), Object(Main\\Module))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(51): Core\\Mvc\\AbstractModule->initialize('Main', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#7 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#8 {main}"}
[2025-10-13 14:23:49] ERROR: str_starts_with(): Argument #1 ($haystack) must be of type string, Core\Http\Request given {"request_uri":"/css/bootstrap.min.css.map","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php","line":33,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(33): str_starts_with(Object(Core\\Http\\Request), '/')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\UI\\Layout.php(19): Core\\UI\\Layout->isActive('/')\n#2 C:\\xampp\\htdocs\\new\\app\\Main\\Provider\\ViewServiceProvider.php(42): Core\\UI\\Layout->addNav('Dashboard', 'calendar3', '/')\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Events\\Manager.php(57): Main\\Provider\\ViewServiceProvider->Main\\Provider\\{closure}(Object(Core\\Events\\Event))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\AbstractModule.php(69): Core\\Events\\Manager->trigger(Object(Core\\Events\\Event), Object(Main\\Module))\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(51): Core\\Mvc\\AbstractModule->initialize('Main', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#7 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#8 {main}"}
[2025-10-13 14:47:23] ERROR: Object of class Core\Forms\Form could not be converted to string {"request_uri":"/user/edit/4","user_id":null,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\form.phtml","line":7,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include()\n#1 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(241): Core\\Mvc\\View->render('User/user/form', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(164): Core\\Mvc\\Controller->render('User/user/form', Array)\n#6 [internal function]: User\\Controller\\UserController->editAction()\n#7 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#9 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#10 {main}"}
[2025-10-13 23:11:10] ERROR: Undefined variable $title {"request_uri":"/user/create","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml","line":4,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml(4): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 4)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('main/form', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(74): User\\Controller\\AbstractController->render('main/form', Array)\n#7 [internal function]: User\\Controller\\UserController->createAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 23:11:12] ERROR: Undefined variable $title {"request_uri":"/user/create","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml","line":4,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml(4): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 4)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('main/form', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(74): User\\Controller\\AbstractController->render('main/form', Array)\n#7 [internal function]: User\\Controller\\UserController->createAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 23:11:23] ERROR: Undefined variable $title {"request_uri":"/user/create","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml","line":4,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml(4): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 4)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('main/form', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(74): User\\Controller\\AbstractController->render('main/form', Array)\n#7 [internal function]: User\\Controller\\UserController->createAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 23:11:23] ERROR: Undefined variable $title {"request_uri":"/user/create","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml","line":4,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml(4): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 4)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('main/form', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(74): User\\Controller\\AbstractController->render('main/form', Array)\n#7 [internal function]: User\\Controller\\UserController->createAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-13 23:11:24] ERROR: Undefined variable $title {"request_uri":"/user/create","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml","line":4,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\main\\form.phtml(4): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 4)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('main/form', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(74): User\\Controller\\AbstractController->render('main/form', Array)\n#7 [internal function]: User\\Controller\\UserController->createAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 00:23:16] ERROR: foreach() argument must be of type array|object, bool given {"request_uri":"/user/groups/1","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php","line":172,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(172): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 172)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(190): Core\\Mvc\\Controller->flashMessage('success', false)\n#2 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(48): Core\\Mvc\\Controller->flashSuccess('User added to g...')\n#3 [internal function]: User\\Controller\\UserController->groupsAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-14 00:25:04] ERROR: foreach() argument must be of type array|object, bool given {"request_uri":"/user/groups/1","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php","line":172,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(172): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 172)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(190): Core\\Mvc\\Controller->flashMessage('success', false)\n#2 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(48): Core\\Mvc\\Controller->flashSuccess('User added to g...')\n#3 [internal function]: User\\Controller\\UserController->groupsAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-14 00:26:41] ERROR: foreach() argument must be of type array|object, bool given {"request_uri":"/user/groups/1","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php","line":172,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(172): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 172)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(190): Core\\Mvc\\Controller->flashMessage('success', false)\n#2 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(48): Core\\Mvc\\Controller->flashSuccess('User added to g...')\n#3 [internal function]: User\\Controller\\UserController->groupsAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-14 00:27:42] ERROR: foreach() argument must be of type array|object, bool given {"request_uri":"/user/groups/1","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php","line":172,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(172): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 172)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Controller.php(190): Core\\Mvc\\Controller->flashMessage('success', false)\n#2 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(48): Core\\Mvc\\Controller->flashSuccess('User added to g...')\n#3 [internal function]: User\\Controller\\UserController->groupsAction()\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-14 01:12:05] ERROR: syntax error, unexpected token ",", expecting ";" {"request_uri":"/user","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\config.php","line":31,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#1 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#2 {main}"}
[2025-10-14 01:12:06] ERROR: syntax error, unexpected token ",", expecting ";" {"request_uri":"/user","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\config.php","line":31,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#1 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#2 {main}"}
[2025-10-14 01:12:11] ERROR: syntax error, unexpected token ",", expecting ";" {"request_uri":"/user","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\config.php","line":31,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#1 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#2 {main}"}
[2025-10-14 02:42:16] ERROR: Undefined variable $form {"request_uri":"/login","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\login.phtml","line":9,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\login.phtml(9): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 9)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/login', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AuthController.php(34): User\\Controller\\AbstractController->render('user/login')\n#7 [internal function]: User\\Controller\\AuthController->loginAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 02:42:16] ERROR: Undefined variable $form {"request_uri":"/login","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\login.phtml","line":9,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\login.phtml(9): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 9)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/login', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AuthController.php(34): User\\Controller\\AbstractController->render('user/login')\n#7 [internal function]: User\\Controller\\AuthController->loginAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 02:42:19] ERROR: Undefined variable $form {"request_uri":"/login","user_id":null,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\login.phtml","line":9,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\login.phtml(9): {closure}(2, 'Undefined varia...', 'C:\\\\xampp\\\\htdocs...', 9)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/login', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AuthController.php(34): User\\Controller\\AbstractController->render('user/login')\n#7 [internal function]: User\\Controller\\AuthController->loginAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 03:16:57] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/login","user_id":5,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Module.php(35): Core\\Di\\Container->get('auth')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Events\\Manager.php(57): User\\Module->User\\{closure}(Object(Core\\Events\\Event))\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(106): Core\\Events\\Manager->trigger(Object(Core\\Events\\Event), Object(Core\\Mvc\\Dispatcher))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 03:16:59] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/login","user_id":5,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Module.php(35): Core\\Di\\Container->get('auth')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Events\\Manager.php(57): User\\Module->User\\{closure}(Object(Core\\Events\\Event))\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(106): Core\\Events\\Manager->trigger(Object(Core\\Events\\Event), Object(Core\\Mvc\\Dispatcher))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 03:17:01] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/login","user_id":5,"ip":"::1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Module.php(35): Core\\Di\\Container->get('auth')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Events\\Manager.php(57): User\\Module->User\\{closure}(Object(Core\\Events\\Event))\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(106): Core\\Events\\Manager->trigger(Object(Core\\Events\\Event), Object(Core\\Mvc\\Dispatcher))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 07:59:38] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:01:46] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:01:47] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:01:48] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:01:49] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:01:50] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:01:52] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:02:15] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:02:16] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:02:24] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:02:28] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:02:51] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:02:51] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:02:52] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:02:52] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:02:55] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:03:16] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:03:17] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:04:37] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:04:38] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:04:39] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:05:36] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:05:36] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:05:38] ERROR: Call to undefined method User\Model\User::groups() {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php","line":25,"trace":"#0 [internal function]: User\\Controller\\UserController->viewAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 08:05:46] ERROR: foreach() argument must be of type array|object, null given {"request_uri":"/user/view/1","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml","line":58,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\views\\user\\user\\view.phtml(58): {closure}(2, 'foreach() argum...', 'C:\\\\xampp\\\\htdocs...', 58)\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#2 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/user/view', Array)\n#6 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\UserController.php(29): User\\Controller\\AbstractController->render('user/user/view', Array)\n#7 [internal function]: User\\Controller\\UserController->viewAction()\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#9 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#10 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#11 {main}"}
[2025-10-14 08:14:36] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(15): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:14:38] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(15): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:15:45] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(15): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:15:47] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(15): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:15:48] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(15): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:18:17] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:18:18] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:18:18] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:18:20] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:18:56] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:18:57] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:30:04] ERROR: syntax error, unexpected variable "$container" {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Provider\\AuthServiceProvider.php","line":20,"trace":"#0 [internal function]: {closure}('User\\\\Provider\\\\A...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php(86): class_exists('\\\\User\\\\Provider\\\\...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php(145): Core\\Di\\Container->build('\\\\User\\\\Provider\\\\...')\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\AbstractModule.php(66): Core\\Di\\Container->register('\\\\User\\\\Provider\\\\...')\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(51): Core\\Mvc\\AbstractModule->initialize('User', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-14 08:30:05] ERROR: syntax error, unexpected variable "$container" {"request_uri":"/css/bootstrap.min.css.map","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Provider\\AuthServiceProvider.php","line":20,"trace":"#0 [internal function]: {closure}('User\\\\Provider\\\\A...')\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php(86): class_exists('\\\\User\\\\Provider\\\\...')\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php(145): Core\\Di\\Container->build('\\\\User\\\\Provider\\\\...')\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\AbstractModule.php(66): Core\\Di\\Container->register('\\\\User\\\\Provider\\\\...')\n#4 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(51): Core\\Mvc\\AbstractModule->initialize('User', Array)\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(64): Core\\Mvc\\App->initModules()\n#6 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#7 {main}"}
[2025-10-14 08:30:14] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 08:30:15] ERROR: Service 'auth' not found or cannot be resolved. {"request_uri":"/profile","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Di\\Container.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\ProfileController.php(16): Core\\Di\\Container->get('auth')\n#1 [internal function]: User\\Controller\\ProfileController->indexAction()\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#4 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#5 {main}"}
[2025-10-14 09:00:43] ERROR: Class "User\Controller\ColorfulTheme" not found {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php","line":42,"trace":"#0 [internal function]: User\\Controller\\BoardController->indexAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 09:00:43] ERROR: Class "User\Controller\ColorfulTheme" not found {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php","line":42,"trace":"#0 [internal function]: User\\Controller\\BoardController->indexAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 09:00:43] ERROR: Class "User\Controller\ColorfulTheme" not found {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php","line":42,"trace":"#0 [internal function]: User\\Controller\\BoardController->indexAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 09:00:43] ERROR: Class "User\Controller\ColorfulTheme" not found {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php","line":42,"trace":"#0 [internal function]: User\\Controller\\BoardController->indexAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 09:00:45] ERROR: Class "User\Controller\ColorfulTheme" not found {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php","line":42,"trace":"#0 [internal function]: User\\Controller\\BoardController->indexAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 09:00:50] ERROR: Class "User\Controller\ColorfulTheme" not found {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php","line":42,"trace":"#0 [internal function]: User\\Controller\\BoardController->indexAction()\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#3 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#4 {main}"}
[2025-10-14 09:26:08] ERROR: Call to undefined method Core\Calendar\Models\CalendarData::hasDataForDate() {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Renderers\\YearViewRenderer.php","line":234,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Renderers\\YearViewRenderer.php(88): Core\\Calendar\\Renderers\\YearViewRenderer->renderMiniMonth(Object(Core\\Calendar\\CalendarConfig), 2025, 1, 20, 60, 240, 190, Object(Core\\Calendar\\Models\\CalendarData))\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Renderers\\AbstractViewRenderer.php(58): Core\\Calendar\\Renderers\\YearViewRenderer->renderBody(Object(Core\\Calendar\\CalendarConfig), Object(Core\\Calendar\\Models\\CalendarData), Object(Core\\Calendar\\Models\\Dimensions))\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Calendar.php(52): Core\\Calendar\\Renderers\\AbstractViewRenderer->render(Object(Core\\Calendar\\CalendarConfig), Object(Core\\Calendar\\Models\\CalendarData))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Calendar.php(133): Core\\Calendar\\Calendar->render()\n#4 C:\\xampp\\htdocs\\new\\app\\views\\user\\board.phtml(1): Core\\Calendar\\Calendar->toHtml()\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#6 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#7 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#9 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/board', Array)\n#10 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php(78): User\\Controller\\AbstractController->render('user/board', Array)\n#11 [internal function]: User\\Controller\\BoardController->indexAction()\n#12 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#13 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#14 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#15 {main}"}
[2025-10-14 09:26:09] ERROR: Call to undefined method Core\Calendar\Models\CalendarData::hasDataForDate() {"request_uri":"/board","user_id":5,"ip":"127.0.0.1","code":0,"file":"C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Renderers\\YearViewRenderer.php","line":234,"trace":"#0 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Renderers\\YearViewRenderer.php(88): Core\\Calendar\\Renderers\\YearViewRenderer->renderMiniMonth(Object(Core\\Calendar\\CalendarConfig), 2025, 1, 20, 60, 240, 190, Object(Core\\Calendar\\Models\\CalendarData))\n#1 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Renderers\\AbstractViewRenderer.php(58): Core\\Calendar\\Renderers\\YearViewRenderer->renderBody(Object(Core\\Calendar\\CalendarConfig), Object(Core\\Calendar\\Models\\CalendarData), Object(Core\\Calendar\\Models\\Dimensions))\n#2 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Calendar.php(52): Core\\Calendar\\Renderers\\AbstractViewRenderer->render(Object(Core\\Calendar\\CalendarConfig), Object(Core\\Calendar\\Models\\CalendarData))\n#3 C:\\xampp\\htdocs\\new\\app\\Core\\Calendar\\Calendar.php(133): Core\\Calendar\\Calendar->render()\n#4 C:\\xampp\\htdocs\\new\\app\\views\\user\\board.phtml(1): Core\\Calendar\\Calendar->toHtml()\n#5 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(66): include('C:\\\\xampp\\\\htdocs...')\n#6 [internal function]: Core\\Mvc\\View->Core\\Mvc\\{closure}()\n#7 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(74): Closure->call(Object(Core\\Mvc\\View))\n#8 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\View.php(42): Core\\Mvc\\View->capture('C:\\\\xampp\\\\htdocs...', Array)\n#9 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\AbstractController.php(41): Core\\Mvc\\View->render('user/board', Array)\n#10 C:\\xampp\\htdocs\\new\\app\\User\\Controller\\BoardController.php(78): User\\Controller\\AbstractController->render('user/board', Array)\n#11 [internal function]: User\\Controller\\BoardController->indexAction()\n#12 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\Dispatcher.php(117): call_user_func(Array)\n#13 C:\\xampp\\htdocs\\new\\app\\Core\\Mvc\\App.php(92): Core\\Mvc\\Dispatcher->dispatch()\n#14 C:\\xampp\\htdocs\\new\\public\\index.php(9): Core\\Mvc\\App->run()\n#15 {main}"}
